//authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const CLASSROOM_CREATE_INIT = 'CLASSROOM_CREATE_INIT'
export const CLASS_CREATION_FAILED = 'CLASS_CREATION_FAILED'
export const CLASS_CREATION_SUCCESS = 'CLASS_CREATION_SUCCESS'
export const CLASSROOM_JOINED = 'CLASSROOM_JOINED'
export const CLASSROOM_LEFT = 'CLASSROOM_LEFT'
