//authentication
export const AUTH_USER_LOGIN_START = 'AUTH_USER_LOGIN_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGIN_FAILED = 'AUTH_USER_LOGIN_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTO_AUTH_FALED = 'AUTO_AUTH_FALED';   
export const AUTH_USER_LOGIN_INIT = 'AUTH_USER_LOGIN_INIT'
export const AUTO_AUTH_INIT = 'AUTO_AUTH_INIT';

export const CLASSROOM_CREATE_INIT = 'CLASSROOM_CREATE_INIT'
export const CLASS_CREATION_FAILED = 'CLASS_CREATION_FAILED'
export const CLASS_CREATION_SUCCESS = 'CLASS_CREATION_SUCCESS'
export const CLASSROOM_JOINED = 'CLASSROOM_JOINED'
export const CLASSROOM_LEFT = 'CLASSROOM_LEFT'
export const ENTERED_CLASS = 'ENTERED_CLASS'
export const CLASSROOM_VERIFICATION_INIT = 'CLASSROOM_VERIFICATION_INIT'
export const CLASSROOM_VERIFY_FAILED_NETWORK = 'CLASSROOM_VERIFY_FAILED_NETWORK'
export const CLASSROOM_NOT_VERIFIRED = 'CLASSROOM_NOT_VERIFIRED'
export const CLASSROOM_VERIFIED = 'CLASSROOM_VERIFIED'
export const CLASSROOM_ASYNC_VERIFICATION_INIT  = 'CLASSROOM_ASYNC_VERIFICATION_INIT'

//cookies
export const ACCEPT_COOKIE = 'ACCEPT_COOKIE';
export const COOKIE_ALREADY_ACCEPTED = 'COOKIE_ALREADY_ACCEPTED';
export const COOKIE_VALIDATE_INIT = 'COOKIE_VALIDATE_INIT';

export const ENVIRONMENT_SWITCH  =  'ENVIRONMENT_SWITCH';